### ISSUE TITLE
"shasum command not found"

### ISSUE THREAD

**Issue by TApplencourt** [andsens/docopt.sh#12]
Thanks a lot for this script! Really useful.

I use it on Centos7 / [Summit](https://www.olcf.ornl.gov/summit/) and shasum is not there. You should use instead `sha256`. 

Thanks again,
Thomas

PS: This is the fix I implemented. I can submit a PR if you want
```bash
    if [[ -x "$(command -v shasum)" ]]; then
        doc_hash=$(printf "%s" "$DOC" | shasum -a 256)
    elif [[ -x "$(command -v shas256sum)" ]]; then
        doc_hash=$(printf "%s" "$DOC" | shasum)
    fi
```

**Comment by andsens** [comment]
Thank you very much :-)

Fixed in master, I'll release a new version in the coming days.

**Comment by andsens** [comment]
There you go, v0.9.16 has been released.

(full automatically even, with github workflows ^^)
