### ISSUE TITLE
Script set -u causes error

### ISSUE THREAD

**Issue by gerardbosch** [andsens/docopt.sh#19]
**docopt.sh version:** 0.9.17

Hi @andsens, I've observed that when setting the following in scripts that are using docopt.sh, they fail:

```bash
set -u
```
or usually

```bash
set -euo pipefail
```

I tried to reproduce it with the demo in the README, so just setting the above flag after the shebang, then run and the following error shows when the script is run:

```console
❯ ./naval.sh                           
./naval.sh: line 85: best_match_idx: unbound variable
./naval.sh: line 125: move: unbound variable


❯ ./naval.sh Olympia move 1 5 --speed 8
./naval.sh: line 82: match_count: unbound variable
./naval.sh: line 125: move: unbound variable
```

I'm usually adding the `set -eu ...` as good practice for scripts. Is that incompatible in some sense with docopt or is it an issue?

Cheers!

**Comment by andsens** [comment]
Hi @gerardbosch 

OK, so I have looked at the option and examined what it would improve if enabled per default in docopt.sh. My conclusion is: not much. If you look at this function for example: https://github.com/andsens/docopt.sh/blob/d5a03f94adf8fd16ffef69e9e120fa6e1ec2af5f/docopt_sh/docopt.sh#L286-L308
The variables are in fact declared, just not bound to a value, which is what 'set -u' is testing. If `set -u` were to test for *undeclared* variables, that'd be useful (i.e. avoid setting a global variables if you mean local ones). I don't see how erroring out on uninitialized variables improves the code quality though (besides, everything is already linted with [shellcheck](https://github.com/andsens/docopt.sh/blob/d5a03f94adf8fd16ffef69e9e120fa6e1ec2af5f/.github/workflows/test.yaml#L26-L29)).  
So I propose you work around this by simply disabling the option while running docopt:
```
eval "$(set +u; docopt "$@")"
```

**Comment by gerardbosch** [comment]
Hi! Thanks for checking this. I see what you mean and thanks for the workaround :smiley:

**Comment by gerardbosch** [comment]
Do you think it would be a good idea to show that on the README as the default command? It could avoid other people finding the same problem.

**Comment by andsens** [comment]
I honestly don't. There are a plethora of options you can set that change the behavior of bash ([`set options`](https://tldp.org/LDP/abs/html/options.html), [`shopt options`](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html)), and then there are a dozen other things you could do that break the script, it's just not feasible to document every possible way you can break and then unbreak docopt.sh.

**Comment by gerardbosch** [comment]
I see your point 👍  Hopefully this ticket will be enough to document the `set -u` behaviour for others landing here :)

**Comment by gerardbosch** [comment]
I've followed your recommendation, and while using `eval "$(set +u; docopt "$@")"` works fine, it seems that shows a kind of false warning/error, which looks confusing: _"No invocations of docopt found, check your script to make sure this is correct."_

```console
❯ docopt.sh naval-fate.sh
naval-fate.sh No invocations of docopt found, check your script to make sure this is correct.
docopt.sh is invoked with `eval "$(docopt "$@")"`.
naval-fate.sh has been updated.

❯ docopt.sh naval-fate.sh
naval-fate.sh No invocations of docopt found, check your script to make sure this is correct.
docopt.sh is invoked with `eval "$(docopt "$@")"`.
The parser in naval-fate.sh is already up-to-date.
```

For the rest, it did the trick :smile:

**Comment by gerardbosch** [comment]
For anyone else landing here: If you want to use `set -u` in your script, another option is to set it right after `eval "$(docopt "$@")"`. As typically, the parser-related code will stay at the top of your script.

This way, the `-u` option, will not affect the docopt.sh generated code, and you just call `eval` as usual :)
