### ISSUE TITLE
Mechanism to stop processing command line arguments

### ISSUE THREAD

**Issue by gerardbosch** [andsens/docopt.sh#20]
Hi there!

I'm not very sure if the following should be ever possible, but we faced with this little problem and thought may worth to open an issue :)

We'd like to tell somehow, that the generated parser stops processing options. I don't know if using a delimiter like `--` could help.

The use case is an script that's using `docopt.sh` to parse just a piece of the options given, and internally is calling an underlying command with some other options passed to the script's CLI:

```console
resticw -p profileX stats latest --cache-dir=/tmp/cache
```

The goal would be to separate somehow the options that are for the outer script (the ones that need to be parsed), to the rest of the line. So in the above example, only the `-p profileX` option would be parseable by `docopt.sh`, while the rest should not.

When running the above command, we get the usage help error, as in the example `--cache-dir` is not something defined as an option for the script (full DOC below).

The following works just fine:

```console
resticw -p profileX stats latest
```

Thanks!

---

https://github.com/erikw/restic-systemd-automatic-backup/blob/03d9399686d8d37188a0c100f3080f5a612df0d2/bin/resticw#L3

```bash
DOC="A little wrapper over restic just to handle profiles and environment loading.

Usage:
  resticw [options] <restic_arguments_line>...

  The <restic_arguments_line> is just the regular unwrapped restic command arguments, e.g. stats latest

Options:
  -p --profile=<name>        Specify the profile to load or use default [default: default].

Examples:
  resticw --profile profileA snapshots
  resticw stats latest  # this will use the profile: default
"
```

**Comment by gerardbosch** [comment]
Hi again :)

In this comment on this thread: https://github.com/erikw/restic-systemd-automatic-backup/pull/71#issuecomment-1036025301 it come up the idea or possibility of `docopt.sh` offering an optional feature to do a `strict` order parsing of arguments.

Do you think that would be feasible or make sense for docopt? For our particular use case to use it as a wrapper with added functionality for another tool, it would be useful.

Feel totally free to close this issue if you think this is not gonna happen, just wanted to share the ideas :)

Thank you!

**Comment by andsens** [comment]
Take a look at the [parser options](https://github.com/andsens/docopt.sh#parser-options). Specifically `DOCOPT_OPTIONS_FIRST=true`.  
Provided that the first argument to restic is a subcommand and not an option you should be able to omit the `--`.
So this will work `resticw -p default snapshot -c -h whatever`.  
This won't work `resticw -p default -h snapshot -c whatever`.

**Comment by gerardbosch** [comment]
Awesome :clap: :clap: :clap: 
My fault, I didn't realize that was possible! Thanks a lot Anders for your support :)

I'm closing this :smiley:
