### ISSUE TITLE
Support short option for --version?

### ISSUE THREAD

**Issue by indigoviolet** [andsens/docopt.sh#21]
Thank you for this library, it is really useful.

It was a bit surprising that `-h` and `--help` both work, but not `-v` or `-V` in addition to `--version`. Would be nice for the short version to be supported as well.

**Comment by indigoviolet** [comment]
nevermind, this works. I must be mistaken.

**Comment by andsens** [comment]
It works, but only if you document it. Both `--help, -h` and `--version` can be left out of the docs and still work, but only if you document `--version` in `Options:` as `--version, -v` will you get the desired behavior.  
This is in line with how the reference implementation does it, and it kind of makes sense. `-h` is a well known short-option for `--help`, but `-v` could mean `--verbose`, `--value`, or `--invert` (grep), so it's not as clear-cut for that one.
