### ISSUE TITLE
Suggestion: support for debugging 

### ISSUE THREAD

**Issue by indigoviolet** [andsens/docopt.sh#22]
I think it would nice to have a built-in mechanism to dump all recognized options and their parsed values. This could be a function included with the parser (say if DOCOPT_INCLUDE_DEBUG=true). I think it will be helpful to someone inexperienced in bash scripting, as well as a good way to show what variables are being defined etc. I would suggest including the option name, the variable name, and its value.

**Comment by andsens** [comment]
Hm, definitely missing in the documentation, but the feature is already there: Just remove the `eval $()` from `eval "$(docopt "$@")"` (just run `docopt "$@"`), then you see exactly what would be assigned :-)
