### ISSUE TITLE
describe your docopt parser behavior and class role

### ISSUE THREAD

**Issue by Sylvain303** [andsens/docopt.sh#8]
It seems your parser doesn't use [python docopt](https://github.com/docopt/docopt/blob/master/docopt.py) for parsing bash `$DOC`

I also realized than docopt installed from `pip install docopt` (0.6.2) is different from the code available on github.

Could you please explain the way you parse bash `$DOC` usage from bash script, and the goal of each class?

I started to analyze you code, parsing:

* main code will call [docopt_sh](https://github.com/andsens/docopt.sh/blob/master/docopt_sh/__main__.py#L46)
  *  docopt_sh() create an instance of [`Script`](https://github.com/andsens/docopt.sh/blob/95d5d0d9adb525a5f30191ae52f85d2b08c7454b/docopt_sh/script.py#L11) object which use a [`Doc`](https://github.com/andsens/docopt.sh/blob/95d5d0d9adb525a5f30191ae52f85d2b08c7454b/docopt_sh/script.py#L129) object to extract docopt part from the bash source script
     * `Doc()`  extracts bash `$DOC` string which is matched from this [regexp](https://github.com/andsens/docopt.sh/blob/95d5d0d9adb525a5f30191ae52f85d2b08c7454b/docopt_sh/script.py#L134)
     * `Doc` holds extracted part of the docopt string
   * `Script()` object then passes the `doc` instance to [`Guards`](https://github.com/andsens/docopt.sh/blob/95d5d0d9adb525a5f30191ae52f85d2b08c7454b/docopt_sh/script.py#L18) object which I don't know the role yet.

**Comment by andsens** [comment]
All `$DOC` parsing happens in `doc_ast.py`, which is just a slimmed-down version of docopt.py with a few modifications.
`bash.py` is bash helpers (where `Code` represents bash code), `parser.py` represents the bash parser we generate, and `node.py` represent the AST nodes in the parsed `$DOC`.  
`script.py` handles the management of the script that is passed to `docopt.sh`, meaning parsing, finding the existing parser, checking for issues, and inserting the generated parser. A `Guard` is one of the comment lines delineating the generated parser (top & bottom).
